//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustNo { get; set; }
        public string CustName { get; set; }
        public string CustAddress { get; set; }
        public int CustPcode { get; set; }
        public string InterestCode { get; set; }
    
        public virtual Interest Interest { get; set; }
    }
}
